class FileId:
    ...

class QueryCompiler:
    def __init__(self) -> None: ...
    def set_schema(self, schema: str) -> None: ...
    def add_executable(self, contents: str) -> FileId: ...
    def validate(self) -> bool: ...
    def validate_file(self, file_id: FileId) -> bool: ...
    def add_validate(self, contents: str) -> bool: ...

    def gql_core_ast(self, file_id: FileId): ...
    def gql_core_ast_mirror(self, file_id: FileId): ...