class Document:
    ...

class QueryCompiler:
    def __init__(self, schema: str) -> None: ...
    def parse(self, query: str) -> Document: ...
    def validate(self, document: Document) -> bool: ...
    def add_validate(self, contents: str) -> bool: ...

    def gql_core_ast(self, document: Document): ...
    def gql_core_ast_mirror(self, document: Document): ...